#!/usr/bin/env python
# encoding: utf-8
"""
setupTools.py

Created by José Sánchez-Gallego on 25 Nov 2013.
Copyright (c) 2013. All rights reserved.
Licensed under a 3-clause BSD license.

"""

import os


_VERSION_TEMPLATE = """
# Autogenerated version file for {packageName}

version = {version!r}

major = {major}
minor = {minor}
release = {release}

"""


def generateVersion(packageName, version, release):

    major = version.split('.')[0]
    minor = version.split('.')[1]

    versionStr = _VERSION_TEMPLATE.format(packageName=packageName,
                                          version=version,
                                          major=major,
                                          minor=minor,
                                          release=release)

    versionFile = os.path.join(packageName, 'version.py')
    with open(versionFile, 'w') as unit:
        unit.write(versionStr)
